services:
  - type: web
    name: gridnest-web-solution
    env: node
    region: singapore
    buildCommand: npm install
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
